###_________________########
##/////////\\\\\\\\\########
#//////////\\\\\\\\\\#######
#//// Xiavic Core \\\\######
#\\\\\ Plugin 2.0 ////######
#\\\\\\\\\\//////////#######
##\\\\\\\\\/////////########
###\\\\\\\\////////#########
####\\\\\\\///////##########
#####\\\\\\//////###########
######\\\\\/////############
#######\\\\////#############
#######\\_|_//##############


##############################
######## !! CONFIG !! ########
##############################
#Economy
Balance_Check: 60

#Private Warps
PWCooldown: 300
#If set to true, players will still need the permission node.
CanShare: false

#Teleport
TpaCooldown: 5
Tpa_Timeout: 60

#Fun
PonyCooldown: 60
AnnoyCooldown: 600