name: XiavicCore
main: Main.mainClass
authors: [Imhandmade, Kerlab, VottusCode]
version: 2.0
commands:
  clear:
    usage:
    description:
  ec:
    usage:
    description:
  feed:
    usage:
    description:
  heal:
    usage:
    description:
  gamemode:
    usage:
    description:
    aliases: gm
  setspawn:
    usage:
    description:
  spawn:
    usage:
    description:
  tpa:
    usage:
    description:
  tpaccept:
    usage:
    description:
  tpdeny:
    usage:
    description:
  rtp:
    usage:
    description:
  argh:
    usage:
    description: